networks:
  sistd-net:
    name: sistd-net
    driver: bridge

services:
  sistd-n8n:
    container_name: sistd-n8n
    image: docker.n8n.io/n8nio/n8n:1.111.1
    restart: always
    ports:
      - 9000:5678
    user: root # Executa o entrypoint como root para instalar utilitários
    entrypoint: ["/setup/docker-entrypoint.sh"]
    environment:
      # Autenticação
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE:-true}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-user}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD:-password}
      
      # Configurações básicas
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=${N8N_PORT:-5678}
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - N8N_EDITOR_BASE_URL=http://${N8N_HOST:-localhost}:${N8N_PORT:-5678}/
      - N8N_EMAIL_MODE=

      # Serviços externos
      - GEMINI_API_KEY
      - MONGO_CONNECTION_STRING
      - TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN
      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/.n8n:/home/node/.n8n
      - ./volumes/shared:/data/shared
      - ./volumes/local-files:/files
      - ./setup:/setup
      
    networks:
      - sistd-net

  sistd-redis:
    container_name: sistd-redis
    image: redis:8.2.2
    restart: always
    command: redis-server --port 6379 --appendonly yes
    volumes:
      - ./volumes/sistd-redis:/data
    networks:
      sistd-net:
        aliases:
          - sistd-redis
    ports:
      - 9001:6379

  sistd-api-backend:
    container_name: sistd-api-backend
    image: node:20-alpine
    restart: always
    working_dir: /usr/src/app
    command: sh -c "npm install && npm start"
    volumes:
      - ./api-backend:/usr/src/app
    ports:
      - 9002:3002
    networks:
      - sistd-net
    env_file:
      - ./api-backend/.env.api